= Controller

* MVC 패턴에서 `Controller` 역할
** 요청 처리 및 흐름 제어 담당
* Front Controller 패턴에서 `Command` interface 구현 클래스에 해당
** 실제 웹 요청을 처리하는 역할

== Controller 구현

=== @Controller

* stereo type bean 중 하나: component scan 과정을 통해 자동으로 bean 등록

[source,java]
----
@Controller                         // <-- Controller 임을 지정
public class HomeController {
    @GetMapping("/")                // <-- HTTP Method 지정, URL 맵핑
    public String index() {
        return "index";             // <-- view 이름 지정
    }
}

----

== Controller 구현 (2)

=== @RestController

* `@RestController` = `@Controller` + `@ResponseBody`
* `@Controller`가 view 이름을 반환하면 `ViewResolver`가 view를 처리하는 반면
* `@RestController`는 `ViewResolver`가 아닌 `HttpMessageConverter`가 응답 객체를 처리

[source,java]
----
@RestController
@RequestMapping("/persons")
public class PersonController {
    /*
            GET /persons/12345

            HTTP/1.1 200 OK
            Content-type: application/json;charset=UTF-8

            {
                "name": "dongmyo",
                "age": 19,
                "address": "Ulsan, Korea"
            }
     */
    @GetMapping("/{id}")
    public Person getPerson(@PathVariable Long id) {
        // ...
    }

    /*
            POST /persons
            {
                "name": "dongmyo",
                "age": 19,
                "address": "Ulsan, Korea"
            }

            HTTP/1.1 201 Created
     */
    @PostMapping
    @ResponseStatus(HttpStatus.CREATED)
    public void add(@RequestBody Person person) {
        // ...
    }
}
----

[source,java]
----
@RequestMapping(value = "/persons")
----

=== `@RequestMapping`을 통한 HTTP Method 맵핑

[source,java]
----
@RequestMapping(value = "/persons", method=RequestMethod.GET)
@RequestMapping(value = "/persons", method=RequestMethod.POST)
@RequestMapping(value = "/persons", method=RequestMethod.PUT)
@RequestMapping(value = "/persons", method=RequestMethod.DELETE)
@RequestMapping(value = "/persons", method=RequestMethod.PATCH)
@RequestMapping(value = "/persons", method=RequestMethod.HEAD)
@RequestMapping(value = "/persons", method=RequestMethod.OPTIONS)
@RequestMapping(value = "/persons", method=RequestMethod.TRACE)
----

=== HTTP Method 맵핑은 줄여서

* `@GetMapping` *==* `@RequestMapping(method=RequestMethod.GET)`
* `@PostMapping` *==* `@RequestMapping(method=RequestMethod.POST)`
* `@PutMapping` *==* `@RequestMapping(method=RequestMethod.PUT)`
* `@DeleteMapping` *==* `@RequestMapping(method=RequestMethod.DELETE)`
* `@PatchMapping` *==* `@RequestMapping(method=RequestMethod.PATCH)`

== Request Mapping (`params`)

=== request parameter와 연결하는 방법

* *id* parameter가 있는 경우에만
[source,java]
----
@RequestMapping(method = RequestMethod.GET, params = { "id" })
----

* *id* parameter가 없는 경우에만

[source,java]
----
@GetMapping(params = { "!id" })
----

* *type* parameter 값이 *raw*인 경우에만

[source,java]
----
@GetMapping(params = "type=raw")
----

* *type* parameter 값이 *raw*가 아닌 경우에만

[source,java]
----
@GetMapping(params = "type!=raw")
----

== Controller Method

=== Ex.)

[source,java]
----
@GetMapping("/")
public String index() {             // return type: String, method argument: 없음
    return "index";
}
----

[source,java]
----
@GetMapping("/{id}")
public Person getPerson(@PathVariable Long id) {        // return type: Person
    // ...                                              // method argument: @PathVariable
    return person;
}
----

[source,java]
----
@PostMapping
public String doLogin(Member loginInfo, HttpSession session) {    // return: `redirect:'
    // ...                                                        // method argument: HttpSession
    return "redirect:/login";
}
----

== Controller Method에서 사용 가능한 method argument

* HttpServletRequest, HttpServletResponse, HttpSession, WebRequest
* Locale
* InputStream, OutputStream, Reader, Writer
* `@PathVariable`, `@RequestParam`, `@RequetHeader`, `@CookieValue`, `@Value`
* Map, Model, ModelMap, `@ModelAttribute`, `@RequestBody`
* Errors, BindingResult, …

== Controller Method에서 사용 가능한 return type

* ModelAndView, View
* Map, Model, ModelMap
* String
* void
* `@ResponseBody`
* POJO

== Model 이용하기

* 개발자가 직접 request.setAttribute를 이용해서 전달해도 되지만 전달 되는 부분을 추상화한 것이 Model 입니다.

=== Model로 이용할 수 있는 type

* `java.util.Map` interface
* `org.springframework.ui.Model` interface
* `org.springframework.ui.ModelMap` class

=== 실제 처리되는 내용

* `Model`에 설정한 속성(attribute)이 `View`에 `request.attribute` 로 전달됨

== 실습

=== 앞서 신규 프로젝트 생성해서 만들었던 NowController

* 여러가지 Model을 이용해서 다시 만들어보기

== ModelAndView

=== `ModelAndView` = `Model` + `View`

[source,java]
----
@GetMapping("/some-request")
public ModelAndView doSomething() {
    ModelAndView mav = new ModelAndView("viewName");
    mav.addObject("name", "value");
    // ...

    return mav;
}
----

== 요청 parameter 받아오기 (`@RequestParam`)

=== @RequestParam

* 요청 URL의 Query String을 처리하기 위한 어노테이션

=== Ex.)

* 요청 URL

----
GET [http://localhost:8080/persons?order=100](http://localhost:8080/persons?order=100)
----

* Controller Method

[source,java]
----
@GetMapping("/persons")
public List<Person> getPersons(@RequestParam(name="order") String order) {
    // ...
}
----

== 요청 URL의 가변 인자 가져오기 (`@PathVariable`)

=== @PathVariable

* 요청 URL의 Resource(Path)을 처리하기 위한 어노테이션
** `@RequestMapping` 의 path 에 변수명을 입력받기 위한 place holder 가 필요함

=== Ex.)

* 요청 URL

----
GET http://localhost:8080/persons/99499102
----

* Controller Method

[source,java]
----
@GetMapping("/persons/{personId}")
public List<Person> getPersons(@PathVariable(name="personId", required=true) Long personId) {
    // ...
}
----

== 요청 Header 값 읽어오기 (`@RequestHeader`)

=== @RequestHeader

* 요청의 HTTP 헤더를 처리하기 위한 어노테이션

=== Ex.)

* 요청

----
GET /some-request HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
----

* Controller Method

[source,java]
----
@GetMapping("/some-request")
public List<User> getUsers(@RequestHeader(name = "User-Agent") String userAgent) {
    // ...
}
----

== Cookie 값 읽어오기 (`@CookieValue`)

=== @CookieValue

* HTTP 쿠키를 처리하기 위한 어노테이션

=== Ex.)

[source,java]
----
@GetMapping("/some-request")
public List<Person> getPersons(@CookieValue(name = "SESSION") String sessionId) {
    // ...
}
----