= MyBatis란?

* 마이바티스는 개발자가 지정한 SQL, 저장프로시저 그리고 몇가지 고급 매핑을 지원하는 퍼시스턴스 프레임워크이다.
* 마이바티스는 JDBC로 처리하는 상당부분의 코드와 파라미터 설정및 결과 매핑을 대신해준다.
* 마이바티스는 데이터베이스 레코드에 원시타입과 Map 인터페이스 그리고 자바 POJO 를 설정해서 매핑하기 위해 XML과 애노테이션을 사용할 수 있다.

== dependency

----
<!-- jdbc -->
<dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-jdbc</artifactId>
</dependency>

<!-- mybatis -->
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis</artifactId>
    <version>3.5.13</version>
</dependency>

<!-- mybatis-spring -->
<dependency>
    <groupId>org.mybatis</groupId>
    <artifactId>mybatis-spring</artifactId>
    <version>2.1.0</version>
</dependency>

----

== MyBatis SqlSessionFactory 생성

* 모든 마이바티스 애플리케이션은 SqlSessionFactory 인스턴스를 사용합니다.
* SqlSessionFactory인스턴스는 SqlSessionFactoryBuilder를 사용하여 만들수 있습니다.
* SqlSessionFactoryBuilder는 XML설정파일에서 SqlSessionFactory인스턴스를 빌드할 수 있다.
* 마이바티스는 클래스패스와 다른 위치에서 자원을 로드하는 것으로 좀더 쉽게 해주는 Resources 라는 유틸성 클래스를 제공합니다.

== MyBatis SqlSession 생성

* SqlSessionFactory 를 이용하여 SqlSession 인스턴스를 만들수 있습니다.
* SqlSession 은 데이터베이스에 대해 SQL명령어를 실행하기 위해 필요한 모든 메소드를 가지고 있습니다.
* SqlSession 인스턴스를 통해 직접 SQL 구문을 실행할 수 있다.

=== OLD

----
try (SqlSession session = sqlSessionFactory.openSession()) {
  Student student = session.selectOne("com.nhnacademy.edu.jdbc1.mybatis.StudentMapper.selectStudent", 1);
}
----

=== NEW - mapper interface를 사용하는 방식

----
try (SqlSession session = sqlSessionFactory.openSession()) {
  StudentMapper mapper = session.getMapper(StudentMapper.class);
  Student student = mapper.selectStudent(1);
}
----

== Scope 와 생명주기

=== SqlSessionFactory

* SqlSessionFactory는 애플리케이션을 실행하는 동안 존재해야만 합니다.
* 애플리케이션이 실행되는 동안 여러 차례 SqlSessionFactory 를 다시 빌드하지 않는 것이 가장 좋은 구성입니다.
* SqlSessionFactory 의 가장 좋은 스코프는 애플리케이션(싱글턴) 스코프입니다.

=== SqlSession

* *각 쓰레드는 자체적으로 SqlSession인스턴스를 가져야 합니다.*
* SqlSession인스턴스는 공유되지 않고 쓰레드에 안전하지도 않기 때문에 가장 좋은 스코프는 요청 또는 메소드 스코프입니다.
* SqlSession 을 static 필드나 클래스의 인스턴스 필드로 지정해서는 안됩니다.
* 서블릿 프레임워크의 HttpSession 과 같은 관리 스코프에 둬서도 안됩니다.
* 웹 프레임워크를 사용한다면 HTTP 요청과 유사한 스코프에 두는 것으로 고려해야 합니다.
** 달리 말해서 HTTP 요청을 받을때마다 만들고 응답을 리턴할때마다 SqlSession 을 닫을 수 있다.
** SqlSession 을 닫는 것은 중요합니다. 언제나 finally 블록에서 닫아야만 합니다.

----
try (SqlSession session = sqlSessionFactory.openSession()) {
  // do work
}
----

=== Mapper 인스턴스

* Mapper는 매핑된 구문을 바인딩 하기 위해 만들어야 할 인터페이스입니다.
* *mapper 인스턴스의 가장 좋은 스코프는 SqlSession 과 동일합니다.*
* mapper 인스턴스의 가장 좋은 스코프는 메소드 스코프입니다.
** 사용할 메소드가 호출되면 생성되고 끝납니다.

----
try (SqlSession session = sqlSessionFactory.openSession()) {
  BlogMapper mapper = session.getMapper(BlogMapper.class);
  // do work
}
----

=== MybatisConfig.java

[source,java]
----
@RequiredArgsConstructor
@Configuration
@MapperScan(basePackages="com.nhnacademy.todo.mapper.**")
public class MybatisConfig {
    private final DataSource dataSource;

    @Bean
    public SqlSessionFactoryBean sqlSessionFactoryBean() throws Exception {
        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
        SqlSessionFactoryBean sessionFactory = new SqlSessionFactoryBean();
        sessionFactory.setDataSource(dataSource);
        sessionFactory.setMapperLocations(resolver.getResources("classpth*:**/maps/*.xml"));
        //camelcase 설정
        //https://mybatis.org/mybatis-3/configuration.html
        sessionFactory.getObject().getConfiguration().setMapUnderscoreToCamelCase(true);
        return sessionFactory;
    }
}
----

=== pom.xml

* maven compile &lt;- xml 파일 포함하기

----
<resources>
    <resource>
        <directory>src/main/resources</directory>
    </resource>
    <resource>
        <directory>src/main/java</directory>
        <includes>
            <include>**/*.xml</include>
        </includes>
    </resource>
</resources>
----