= 게시판 만들기

* Spring MVC기반 Web Application

== 요구사항
* MyBatis
* maven project
* packaging: war

* Spring mvc framework 기반으로
** view 페이지는 thymeleaf를 사용
* 모든 메세지는 영어, 한국어 2개 언어 지원
** 언어 변경 가능
* 로그인/로그아웃
** 로그인하지 않고 다른 기능 사용 불가
** BindingResult를 활용해서 개발하기
* 사용자 등록/수정/삭제/조회
* 게시물 등록/수정/삭제/조회
* 게시물 조회 성공 시 조회 수 업데이트
** 동일 사용자가 게시물 조회 : 24시간 내에 조회한 게시물은 카운트를 +1로 처리 합니다.
** 필터 + 쿠키를 이용해서 구현합니다.
* 사이트 방문자수 카운트
** 사이트 방문자 수는 1시간내에 +1 로 처리합니다.
** 쿠키와 필터를 이용해서 구현합니다.
* 페이지가 로딩되는 시간을 모든 페이지 화면에 표시합니다.
** Interceptor 를 이용해서 구현합니다.

=== 사용자

* 사용자 속성
** 아이디
** 비밀번호
** 이름
** 프로필 이미지
** 사용자는 미리 100명 등록합니다.
* 특별한 사용자 - 관리자
** 아이디: admin
** 비밀번호: 12345
** 이름: 관리자
** 프로필 이미지 :
* 프로필 이미지가 존재하지 않다면 : /resources/no-image.png를 리턴 합니다.
* 관리자는 초기화 시점에 등록
* 사용자 아이디, 비밀번호는 로그인 시에만 사용
** 다른 사용자가 조회를 할 경우에는 아이디, 비밀번호는 보여주지 않는다는 의미입니다.
* 사용자 조회 화면에서는 이름과 프로필 이미지만 보여준다
** 기능적으로 사용자를 구분하기 위해 아이디 사용은 가능

* 사용자 interface

[source,java]
----
public interface User {
    String getId();
    void setId(String id);

    String getPassword();
    void setPassword(String password);

    String getName();
    void setName(String name);

    String getProfileFileName();
    void setProfileFileName(String profileFileName);
}

----

* 사용자를 등록/수정/삭제/조회 시에 `UserReposity` 사용
** `UserReposity` 구현은 **메모리 기반 자료 구조 (List, Map 등)** 사용

[source,java]
----
public interface UserRepository {
    void add(User user);
    void modify(User user);
    User remove(String id);

    User getUser(String id);
    List<User> getUsers();
}
----

=== 게시물

* 게시물 속성
** 게시물 아이디 (long type 숫자 값)
** 제목
** 본문 (plain text)
** 작성자 아이디
** 작성 시각 (기본값은 현재 시각)
** 조회 수
* 게시물 interface

[source,java]
----
public interface Post {
    long getId(); // 게시물을 등록하면 id 값을 반환
    void setId(long id);

    String getTitle();
    void setTitle(String title);

    String getContent();
    void setContent(String content);

    String getWriterUserId();
    void setWriterUserId(String writerUserId);

    LocalDateTime getWriteTime();
    void setWriteTime(LocalDateTime writeTime);

    int getViewCount();
    void increaseViewCount();
}
----

* 게시물을 등록/수정/삭제/조회 시에 `PostRepository` 사용

[source,java]
----
public interface PostRepository {
    long register(Post post);
    void modify(Post post);
    Post remove(long id);

    Post getPost(long id);
    List<Post> getPosts();
}
----

* 게시물 등록 예제

[source,java]
----
Post post = new ConcretePost();
post.setTitle("제목");
post.setContent("내용");
post.setWriterUserId("marco");
// NOTE: 등록 시 `setWriteTime()`을 호출하지 않으면 현재 시각을 기본값으로 설정

// NOTE: 게시물을 등록하면 repository가 id 값을 반환해야 한다.
long postId = postRepository.register(post);
post.setId(postId);
----

* `PostReposity` 구현을 ServletContext 초기화 시점에 등록해서 사용
** `PostReposity` 구현은 **메모리 기반 자료 구조 (List, Map 등)** 사용

=== 화면 구성

* 로그인하지 않았으면
** 로그인 화면으로 이동
* 로그인한 사용자가
** 관리자면
*** 사용자 목록
**** 사용자 조회
***** 사용자 정보 수정
***** 사용자 삭제
*** 사용자 추가
**** 프로파일 업로드 `POST /profile`
***** Servlet API 3.0 spec 기준으로 구현
***** `commons-fileupload` 라이브러리 사용 금지
** 관리자가 아니면
*** 게시물 목록
**** 게시물 조회
***** 본인이 작성한 게시물이면
****** 게시물 수정
****** 게시물 삭제
***** 작성자 이름을 클릭하면 사용자 조회 화면으로 이동
****** 사용자 조회 화면에는 작성자 이름과 작성자 프로파일 표시
******* `&lt;img src=&#39;/profile?id=&#39;&gt;`
*** 게시물 등록
** 로그아웃
** 현재 방문자수, 로그인한 사용자 수 표시
** 현재 언어 표시
*** 언어 변경 ( ko, en )

=== 게시물,사용자 Pagination 처리

* Pagination (Paging)

** 전체 목록을 **페이지** 단위로 끊어서 보여주는 것
** page: 현재 페이지 번호 (1부터 시작)
** size: 한 페이지에 보여줄 게시물 갯수 (10개)
* Ex.)

** 총 게시물 수: 13개 (1, 2, 3, …, 13)
** 총 페이지 수: 2 페이지
*** 1 페이지: (1, 2, 3, …, 10)
*** 2 페이지: (11, 12, 13)
* `PostRepository`에 Pagination을 위한 메서드 추가

[source,java]
----
public interface PostRepository {
    // ...

    int getTotalCount();
    Page<Post> getPagedList(int page, int size);
}
----

[source,java]
----
public interface Page<T> {
    int getPageNumber();            // 현재 페이지 번호
    int getPageSize();              // 한 페이지에 보여줄 게시물 갯수
    int getTotalPageCount();        // 총 페이지 수

    long getTotalCount();           // 총 게시물 수
    List<T> getList();              // 게시물 목록
}
----

=== Test Code 작성하기

* Controller 통합테스트
* Service 단위테스트
* Sonarqube 테스트커버리지 스크린샷 해서 제출하기
** 50% 이상 .
* Assertj 공식문서
** https://assertj.github.io/doc/
* Mockito 공식문서
** https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html
